spring:
   profiles:
      activve:
      - dev
---
spring:
   profiles: dev #开发环境
   application:
      name: microservicecloud-config-af-dev
---
spring:
   profiles: test #测试环境
   application:
      name: miecroserivcecloud-config-af-test
